// examples/hono/src/App.tsx
import './App.css';
import React, { useEffect, useState } from 'react';

const App = () => {
  const [renderer, setRenderer] = useState('server');

  useEffect(() => {
    setRenderer('client');
  }, []);

  return (
    <div className="content">
      <h1>Rsbuild with React</h1>
      <p>Hello from {renderer}</p>
      <p>Start building amazing things with Rsbuild.</p>
    </div>
  );
};

export default App;

// examples/vue/src/App.vue
<template>
  <div class="content" @click="color = !color">
    <h1>Rsbuild with Vue</h1>
    <p>Start building amazing things with Rsbuild.</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const color = ref(true)
</script>

<style scoped>
content h1 {
  font-size: 3.6rem;
  font-weight: 700;
  /* ok */
  color: v-bind("color ? 'red': 'green'");
  /* no ok */
  color: v-bind('color ? "red": "green"');
}
</style>
