// packages/create-rsbuild/template-vue2-js/src/App.vue
<template>
  <div>
    <h1>Rsbuild + Vue</h1>

    <div class="card">
      <button type="button" @click="count++">count is {{ count }}</button>
      <p>
        Edit
        <code>App.vue</code> to test HMR
      </p>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return { count: 0 };
  },
};
</script>

<style scoped>
.card {
  padding: 2em;
}
</style>

// packages/create-rsbuild/template-react-ts/src/App.tsx
import { useState } from 'react';

const HelloWorld = () => {
  const [count, setCount] = useState(0);

  return (
    <div>
      <h1>Rsbuild + React</h1>

      <div>
        <button type="button" onClick={() => setCount(count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>App.tsx</code> to test HMR
        </p>
      </div>
    </div>
  );
};

export default HelloWorld;
